# Generated by Django 3.0.7 on 2020-06-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameRegistration',
            new_name='PlayerGame',
        ),
    ]
