# Generated by Django 3.0.7 on 2020-06-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200621_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together={('game', 'player')},
        ),
    ]
