# Generated by Django 3.0.7 on 2020-07-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200622_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='addition_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameregistered',
            name='thumb_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
